import type { Pipeline, ProductDrop, RealityMeter } from "@/lib/pipeline/schema";
import type { ExportHealthCheck } from "@/lib/export/schema";
import { deriveEnvExample } from "@/lib/export/docs";

/** Deterministic env-var names this pipeline needs (no values — names only). */
export function requiredEnvVarNames(pipeline: Pipeline): string[] {
  return deriveEnvExample(pipeline)
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith("#"))
    .map((l) => l.split("=")[0])
    .filter(Boolean);
}

export type PrDescriptionInput = {
  pipeline: Pipeline;
  drop: ProductDrop;
  reality: RealityMeter;
  health: ExportHealthCheck;
  destinationPath: string;
  fileCount: number;
  modes: string[];
};

/** Generate a PR body from Flowmind data. NEVER includes secret values — env var NAMES only. */
export function generatePullRequestBody(input: PrDescriptionInput): string {
  const { pipeline, drop, reality, health, destinationPath, fileCount, modes } = input;
  const teams = pipeline.nodes.filter((n) => n.team);
  const sources = pipeline.nodes.filter((n) => n.source || n.type === "input" || n.type === "tool");
  const envVars = requiredEnvVarNames(pipeline);
  const missing = [...new Set([...(reality.missing ?? []), ...(reality.missingData ?? []), ...health.missingItems])];

  const nextSteps = [
    ...envVars.map((e) => `Add env var \`${e}\``),
    ...(drop.missingApis ?? []).map((a) => `Wire ${a}`),
    "Run the pipeline locally (`npm install && npm start`)",
    reality.hardestPart ? `Tackle the hardest part: ${reality.hardestPart}` : "",
  ].filter(Boolean);

  return [
    `## Flowmind Export`,
    ``,
    `### Product`,
    `**${drop.name || pipeline.name}**`,
    drop.pitch || pipeline.description || "",
    ``,
    `### What this PR adds`,
    `Files land under \`${destinationPath}\` (${fileCount} files · ${modes.join(", ")}).`,
    `- Pipeline config (validated graph)`,
    `- ${pipeline.nodes.length} node(s)${teams.length ? `, ${teams.length} crew/team(s)` : ""}`,
    `- Tool / source configs (no secrets)`,
    `- Datasets + data-contract config`,
    `- Runtime example + adapter stubs`,
    `- Output-table / UI-binding config`,
    `- Implementation docs (README, SPEC)`,
    ``,
    `### How to run`,
    "```bash",
    "npm install",
    "npm start  # runs runtime/run-pipeline.ts against example-input.json",
    "```",
    ``,
    `### Required env vars`,
    envVars.length ? envVars.map((e) => `- \`${e}\``).join("\n") : "- _none_",
    `> Copy \`.env.example\` → \`.env.local\` and fill in values. No secrets are committed.`,
    ``,
    `### Sources & integrations`,
    sources.length ? sources.map((n) => `- ${n.title}${n.source?.mode ? ` (${n.source.mode})` : ""}`).join("\n") : "- _none_",
    ``,
    `### Missing pieces`,
    missing.length ? missing.map((m) => `- ${m}`).join("\n") : "- _none flagged_",
    ``,
    `### Reality Meter`,
    `**Score:** ${reality.buildability ?? 0}%${reality.label ? ` · ${reality.label.replace(/_/g, " ")}` : ""}`,
    reality.hardestPart ? `**Hardest part:** ${reality.hardestPart}` : "",
    reality.fastestMvpPath ? `**Fastest MVP:** ${reality.fastestMvpPath}` : "",
    ``,
    `### Next steps`,
    nextSteps.map((s) => `- [ ] ${s}`).join("\n"),
    ``,
    `---`,
    `🤖 Generated by [Flowmind](https://flowmind.app) — AI System Design Studio. Export readiness: ${health.status} (${health.score}%).`,
  ]
    .filter((l) => l !== undefined)
    .join("\n");
}

export function defaultPullRequestTitle(drop: ProductDrop, pipeline: Pipeline): string {
  return `Add Flowmind AI pipeline: ${drop.name || pipeline.name}`;
}

export function defaultBranchName(slug: string): string {
  const stamp = new Date().toISOString().slice(0, 10).replace(/-/g, "");
  return `flowmind/${slug || "pipeline"}-${stamp}`;
}
