import type { Pipeline } from "@/lib/pipeline/schema";
import { hexFor } from "@/lib/ui/colors";
import type { DocsContext } from "./docs";

/**
 * Print-ready visual docs (Prompt 22). Self-contained HTML (inline CSS + inline SVG architecture
 * diagram) styled for "Print → Save as PDF" — the dependency-free way to ship a real PDF. Two
 * audiences: the Founder brief (architecture + node purposes + prompt strategy, hand-to-a-developer
 * quality) and the Client blueprint (visual, non-technical — no prompts or model ids).
 */

function esc(s: unknown): string {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/** An inline SVG of the graph from real node positions + edges. `technical` shows model badges. */
function diagramSvg(p: Pipeline, technical: boolean): string {
  const nodes = p.nodes;
  if (nodes.length === 0) return "";
  const xs = nodes.map((n) => n.position.x);
  const ys = nodes.map((n) => n.position.y);
  const minX = Math.min(...xs);
  const minY = Math.min(...ys);
  const maxX = Math.max(...xs);
  const maxY = Math.max(...ys);
  const W = Math.max(1, maxX - minX) + 220;
  const H = Math.max(1, maxY - minY) + 120;
  const NW = 150;
  const NH = 52;
  const pos = (n: Pipeline["nodes"][number]) => ({ x: n.position.x - minX + 20, y: n.position.y - minY + 20 });

  const edges = p.edges
    .map((e) => {
      const s = nodes.find((n) => n.id === e.source);
      const t = nodes.find((n) => n.id === e.target);
      if (!s || !t) return "";
      const a = pos(s);
      const b = pos(t);
      const sx = a.x + NW;
      const sy = a.y + NH / 2;
      const tx = b.x;
      const ty = b.y + NH / 2;
      const mx = (sx + tx) / 2;
      return `<path d="M ${sx} ${sy} C ${mx} ${sy}, ${mx} ${ty}, ${tx} ${ty}" fill="none" stroke="#8b5cf6" stroke-width="1.5" opacity="0.5"/>`;
    })
    .join("");

  const boxes = nodes
    .map((n) => {
      const a = pos(n);
      const color = hexFor({ color: (n.color as string) || "violet", type: n.type });
      const isTeam = Boolean(n.team);
      const sub = isTeam ? `team · ${n.team?.strategy}` : technical ? esc(n.model) : esc(n.type);
      return `
        <g transform="translate(${a.x},${a.y})">
          <rect width="${NW}" height="${NH}" rx="10" fill="${color}1a" stroke="${color}66" stroke-width="1.5"/>
          <text x="10" y="21" font-size="12.5" font-weight="600" fill="#e8e8f0">${esc(n.title).slice(0, 22)}</text>
          <text x="10" y="38" font-size="10" fill="#9a9aae">${sub}</text>
        </g>`;
    })
    .join("");

  return `<svg viewBox="0 0 ${W} ${H}" width="100%" style="max-width:760px;background:#0c0c14;border-radius:12px" xmlns="http://www.w3.org/2000/svg">${edges}${boxes}</svg>`;
}

function shell(title: string, body: string): string {
  return `<!doctype html><html><head><meta charset="utf-8"/><title>${esc(title)}</title>
<style>
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body { font: 15px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #1a1a24; background: #fff; margin: 0; }
  .page { max-width: 820px; margin: 0 auto; padding: 48px 40px; }
  h1 { font-size: 30px; margin: 0 0 6px; letter-spacing: -0.5px; }
  h2 { font-size: 18px; margin: 32px 0 10px; padding-bottom: 6px; border-bottom: 1px solid #e6e6ee; }
  h3 { font-size: 14px; margin: 16px 0 4px; }
  p { margin: 0 0 10px; }
  .lead { font-size: 17px; color: #44445a; }
  .pill { display: inline-block; background: #f1f0fb; color: #6d28d9; border-radius: 99px; padding: 3px 10px; font-size: 12px; font-weight: 600; margin-right: 6px; }
  .muted { color: #6a6a7e; font-size: 13px; }
  .card { border: 1px solid #e6e6ee; border-radius: 12px; padding: 14px 16px; margin: 8px 0; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
  .meter { height: 8px; background: #eee; border-radius: 99px; overflow: hidden; }
  .meter > div { height: 100%; background: linear-gradient(90deg,#8b5cf6,#22d3ee); }
  .diagram { margin: 14px 0; }
  code { background: #f4f4fa; padding: 1px 5px; border-radius: 4px; font-size: 13px; }
  .foot { margin-top: 40px; color: #9a9aae; font-size: 12px; border-top: 1px solid #e6e6ee; padding-top: 14px; }
  @media print { .page { padding: 24px; } h2 { page-break-after: avoid; } .card { page-break-inside: avoid; } }
</style></head><body><div class="page">${body}<div class="foot">Generated by Flowmind · Print → Save as PDF</div></div></body></html>`;
}

/** Founder brief — architecture + plain-English node purposes + prompt strategy. */
export function founderBriefHtml(ctx: DocsContext): string {
  const p = ctx.pipeline;
  const r = ctx.reality;
  const nodes = p.nodes
    .map((n) => {
      const purpose = n.role || n.description || (n.team ? `Coordinates ${n.team.agents.filter((a) => !a.isController).length} agents (${n.team.strategy}).` : "Processes its inputs into its outputs.");
      const strat = n.prompt
        ? `<div class="muted"><b>Prompt strategy:</b> ${esc(n.prompt).slice(0, 220)}${n.prompt.length > 220 ? "…" : ""}</div>`
        : "";
      return `<div class="card"><h3>${esc(n.title)} <span class="muted">· ${esc(n.team ? `team/${n.team.strategy}` : n.type)} · ${esc(n.model)}</span></h3><p>${esc(purpose)}</p>${strat}</div>`;
    })
    .join("");

  const body = `
    <span class="pill">Founder Brief</span><span class="pill">Real Claude</span>
    <h1>${esc(ctx.drop.name)}</h1>
    <p class="lead">${esc(ctx.drop.pitch || p.description)}</p>
    <p class="muted"><b>For:</b> ${esc(ctx.drop.targetUser || "—")} &nbsp;·&nbsp; <b>Core value:</b> ${esc(ctx.drop.coreValue || "—")}</p>

    <h2>Architecture</h2>
    <div class="diagram">${diagramSvg(p, true)}</div>
    <p class="muted">${esc(ctx.drop.workflowSummary || "Source → Brain → Surface.")}</p>

    <h2>What each part does</h2>
    ${nodes}

    <h2>Is it worth building?</h2>
    <div class="card">
      <h3>Buildability: ${r.buildability}%</h3>
      <div class="meter"><div style="width:${Math.max(0, Math.min(100, r.buildability))}%"></div></div>
      <p style="margin-top:10px"><b>Hardest part:</b> ${esc(r.hardestPart || "—")}</p>
      <p><b>Fastest MVP:</b> ${esc(r.fastestMvpPath || "—")}</p>
      <div class="grid">
        <div><b>Cost risk:</b> ${esc(r.costRisk)}</div>
        <div><b>Complexity risk:</b> ${esc(r.complexityRisk)}</div>
      </div>
      ${r.missing?.length ? `<p style="margin-top:10px"><b>Missing for production:</b> ${esc(r.missing.join(", "))}</p>` : ""}
      ${r.recommendedNext ? `<p><b>Recommended next:</b> ${esc(r.recommendedNext)}</p>` : ""}
    </div>
  `;
  return shell(`${ctx.drop.name} — Founder Brief`, body);
}

/** Client blueprint — visual, non-technical (no prompts, no model ids). */
export function clientBlueprintHtml(ctx: DocsContext): string {
  const p = ctx.pipeline;
  const surfaces = (ctx.drop.keySurfaces ?? ctx.drop.uiSurfaces ?? []).map((s) => `<span class="pill">${esc(s)}</span>`).join("");
  const steps = p.nodes
    .filter((n) => n.type !== "input" && n.type !== "output")
    .map((n, i) => `<div class="card"><h3>${i + 1}. ${esc(n.title)}</h3><p>${esc(n.role || n.description || "Handles one step of the work.")}</p></div>`)
    .join("");
  const outputs = p.outputTables
    .map((t) => `<div class="card"><b>${esc(t.name)}</b><div class="muted">${esc(t.description || `${t.columns.length} fields`)}</div></div>`)
    .join("");

  const body = `
    <span class="pill">Solution Blueprint</span>
    <h1>${esc(ctx.drop.name)}</h1>
    <p class="lead">${esc(ctx.drop.pitch || p.description)}</p>

    <h2>What it does</h2>
    <p>${esc(ctx.drop.coreValue || ctx.drop.workflowSummary || p.description)}</p>
    <div class="diagram">${diagramSvg(p, false)}</div>

    <h2>How it works, step by step</h2>
    ${steps}

    <h2>What you get</h2>
    <div class="grid">${outputs}</div>
    ${surfaces ? `<h2>Where you'll see it</h2><p>${surfaces}</p>` : ""}
  `;
  return shell(`${ctx.drop.name} — Blueprint`, body);
}
