import { toolDefinitionSchema, type ToolCategory, type ToolDefinition } from "./schema";

const RAW: unknown[] = [
  {
    id: "google_places_search",
    name: "Google Places Search",
    description: "Find candidate places, ratings, categories, and location details.",
    category: "places",
    authType: "api_key",
    requiredEnvVars: ["GOOGLE_PLACES_API_KEY"],
    inputSchema: [
      { key: "query", type: "string", required: true },
      { key: "location", type: "string" },
      { key: "radius", type: "number" },
      { key: "type", type: "string" },
    ],
    outputSchema: [{ key: "places", type: "array", description: "Rows of place candidates." }],
    permissions: [{ scope: "places.search", label: "Search places", riskLevel: "low" }],
    costNotes: "Google Places usage-based pricing.",
    testable: true,
    mockable: true,
    fallbackSourceMode: "input_studio",
    fallbackDatasetId: "ds-places-seed",
    liveHandler: { type: "provider_sdk" },
  },
  {
    id: "serpapi_search",
    name: "SerpAPI Search",
    description: "General web search results for research and enrichment.",
    category: "web_search",
    authType: "api_key",
    requiredEnvVars: ["SERPAPI_API_KEY"],
    inputSchema: [
      { key: "query", type: "string", required: true },
      { key: "location", type: "string" },
      { key: "numResults", type: "number" },
    ],
    outputSchema: [{ key: "results", type: "array" }],
    permissions: [{ scope: "web.search", label: "Search the web", riskLevel: "low" }],
    costNotes: "~$0.01 / search, depending on plan.",
    testable: true,
    mockable: true,
    liveHandler: { type: "custom_http", endpoint: "https://serpapi.com/search.json", method: "GET" },
  },
  {
    id: "rentcast_property_lookup",
    name: "RentCast Property Lookup",
    description: "Look up property facts, rent estimates, and rental comps.",
    category: "real_estate",
    authType: "api_key",
    requiredEnvVars: ["RENTCAST_API_KEY"],
    inputSchema: [{ key: "address", type: "string", required: true }],
    outputSchema: [
      { key: "property", type: "object" },
      { key: "rent_estimate", type: "object" },
      { key: "comps", type: "array" },
    ],
    permissions: [{ scope: "property.read", label: "Read property facts", riskLevel: "low" }],
    testable: true,
    mockable: true,
    liveHandler: { type: "custom_http", endpoint: "https://api.rentcast.io/v1/properties", method: "GET" },
  },
  {
    id: "attom_property_lookup",
    name: "ATTOM Property Lookup",
    description: "Look up property facts, assessments, and sales history.",
    category: "real_estate",
    authType: "api_key",
    requiredEnvVars: ["ATTOM_API_KEY"],
    inputSchema: [{ key: "address", type: "string", required: true }],
    outputSchema: [{ key: "property", type: "object" }],
    permissions: [{ scope: "property.read", label: "Read ATTOM property data", riskLevel: "low" }],
    testable: true,
    mockable: true,
    liveHandler: { type: "custom_http", method: "GET", baseUrlEnvVar: "ATTOM_BASE_URL" },
  },
  {
    id: "supabase_query",
    name: "Supabase Query",
    description: "Read rows from the configured Supabase project.",
    category: "database",
    authType: "env_var",
    requiredEnvVars: ["NEXT_PUBLIC_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_ANON_KEY"],
    inputSchema: [
      { key: "table", type: "string", required: true },
      { key: "filter", type: "object" },
      { key: "limit", type: "number" },
    ],
    outputSchema: [{ key: "rows", type: "array" }],
    permissions: [{ scope: "database.read", label: "Read database rows", riskLevel: "medium" }],
    testable: true,
    mockable: true,
    liveHandler: { type: "internal" },
  },
  {
    id: "custom_http_request",
    name: "Custom HTTP Request",
    description: "Call any declared HTTP endpoint with mapped input and output fields.",
    category: "custom_http",
    authType: "custom",
    requiredEnvVars: [],
    inputSchema: [
      { key: "method", type: "string" },
      { key: "url", type: "string", required: true },
      { key: "headers", type: "object" },
      { key: "body", type: "object" },
    ],
    outputSchema: [{ key: "response", type: "object" }],
    permissions: [{ scope: "http.request", label: "Call external HTTP endpoint", riskLevel: "medium" }],
    testable: true,
    mockable: true,
    liveHandler: { type: "custom_http" },
  },
  {
    id: "dataset_lookup",
    name: "Dataset Lookup",
    description: "Read rows from an Input Studio dataset as a live-tool fallback.",
    category: "dataset",
    authType: "none",
    requiredEnvVars: [],
    inputSchema: [
      { key: "datasetId", type: "string", required: true },
      { key: "filter", type: "object" },
      { key: "limit", type: "number" },
    ],
    outputSchema: [{ key: "rows", type: "array" }],
    permissions: [{ scope: "dataset.read", label: "Read seed dataset", riskLevel: "low" }],
    testable: true,
    mockable: true,
    liveHandler: { type: "internal" },
  },
  {
    id: "previous_take_lookup",
    name: "Previous Take Lookup",
    description: "Use a previous run/take output table as this node's input.",
    category: "dataset",
    authType: "none",
    requiredEnvVars: [],
    inputSchema: [
      { key: "takeId", type: "string" },
      { key: "outputTableId", type: "string" },
    ],
    outputSchema: [{ key: "table", type: "object" }],
    permissions: [{ scope: "take.read", label: "Read previous take", riskLevel: "low" }],
    testable: false,
    mockable: true,
    liveHandler: { type: "internal" },
  },
  {
    id: "google_drive_picker",
    name: "Google Drive — Pick Files",
    description: "Let the user select Drive files for this app. Per-file access (drive.file), not your whole Drive.",
    category: "files",
    authType: "oauth",
    requiredEnvVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
    inputSchema: [{ key: "mimeTypes", type: "array" }],
    outputSchema: [{ key: "files", type: "array" }],
    permissions: [{ scope: "drive.file", label: "Access files you select", riskLevel: "medium" }],
    scope: "https://www.googleapis.com/auth/drive.file",
    liveHandler: { type: "internal" },
  },
  {
    id: "google_drive_search",
    name: "Google Drive — Search",
    description: "Search files the app can access by name or type.",
    category: "files",
    authType: "oauth",
    requiredEnvVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
    inputSchema: [{ key: "query", type: "string", required: true }, { key: "mimeTypes", type: "array" }],
    outputSchema: [{ key: "files", type: "array" }],
    permissions: [{ scope: "drive.file", label: "Access files you select", riskLevel: "medium" }],
    scope: "https://www.googleapis.com/auth/drive.file",
    liveHandler: { type: "internal", endpoint: "/api/google-drive/files", method: "GET" },
  },
  {
    id: "google_docs_fetch",
    name: "Google Docs — Fetch Text",
    description: "Export a selected Google Doc as plain text.",
    category: "files",
    authType: "oauth",
    requiredEnvVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
    inputSchema: [{ key: "fileId", type: "string", required: true }],
    outputSchema: [{ key: "title", type: "string" }, { key: "text", type: "string" }, { key: "metadata", type: "object" }],
    permissions: [{ scope: "drive.file", label: "Read selected document", riskLevel: "medium" }],
    scope: "https://www.googleapis.com/auth/drive.file",
    liveHandler: { type: "internal", endpoint: "/api/google-drive/file/[fileId]", method: "GET" },
  },
  {
    id: "google_sheets_read",
    name: "Google Sheets — Read Range",
    description: "Read a range from a selected Google Sheet into rows + headers.",
    category: "sheets",
    authType: "oauth",
    requiredEnvVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
    inputSchema: [{ key: "spreadsheetId", type: "string", required: true }, { key: "range", type: "string" }],
    outputSchema: [{ key: "headers", type: "array" }, { key: "rows", type: "array" }],
    permissions: [{ scope: "drive.file", label: "Read selected spreadsheet", riskLevel: "medium" }],
    scope: "https://www.googleapis.com/auth/drive.file",
    liveHandler: { type: "internal", endpoint: "/api/google-drive/sheets/read", method: "GET" },
  },
];

export const TOOLS: ToolDefinition[] = RAW.map((t) => toolDefinitionSchema.parse(t));

export function getTool(id: string): ToolDefinition | undefined {
  const aliases: Record<string, string> = {
    google_places: "google_places_search",
    rentcast: "rentcast_property_lookup",
    attom: "attom_property_lookup",
    supabase_table: "supabase_query",
    custom_http: "custom_http_request",
  };
  return TOOLS.find((t) => t.id === (aliases[id] ?? id));
}

export function toolsByCategory(category: ToolCategory): ToolDefinition[] {
  return TOOLS.filter((t) => t.category === category);
}
